package dev.drav.glyphworks.grid.connectedblocks;

import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.logging.Logger;

import javax.annotation.Nullable;

import org.joml.Vector3i;
import org.joml.Vector3ic;

import com.hypixel.hytale.assetstore.map.BlockTypeAssetMap;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.protocol.BlockFace;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.BlockType;
import com.hypixel.hytale.server.core.universe.world.World;
import com.hypixel.hytale.server.core.universe.world.connectedblocks.ConnectedBlockRuleSet;
import com.hypixel.hytale.server.core.universe.world.connectedblocks.ConnectedBlocksUtil;

import dev.drav.glyphworks.grid.component.FaceMode;
import dev.drav.glyphworks.grid.component.FacePlane;
import dev.drav.glyphworks.grid.component.GridComponent;
import dev.drav.glyphworks.grid.lookup.GridLookup;
import dev.drav.glyphworks.grid.util.GridFaceUtil;

/**
 * {@link ConnectedBlockRuleSet} for the pipe block. Determines the correct
 * state variant (shape) by inspecting which of the six faces has a compatible
 * adjacent pipe, then maps the resulting direction set to the pre-computed
 * block-type key for that shape.
 *
 * <p>
 * JSON usage (no extra fields required — all 64 state names are resolved
 * programmatically from the base block's State.Definitions):
 * 
 * <pre>
 * "ConnectedBlockRuleSet": { "Type": "Pipe" }
 * </pre>
 *
 * <p>
 * Replace with {@code "Pipe"} type in the codec via
 * {@link ConnectedBlockRuleSet#CODEC}.
 */
public final class PipeConnectedBlockRuleSet extends ConnectedBlockRuleSet {

    private static final Logger LOGGER = Logger.getLogger(PipeConnectedBlockRuleSet.class.getName());

    public static final BuilderCodec<PipeConnectedBlockRuleSet> CODEC = BuilderCodec
            .builder(PipeConnectedBlockRuleSet.class, PipeConnectedBlockRuleSet::new).build();

    /**
     * Direction labels in N→S→E→W→U→D declaration order — must stay in sync
     * with the state names generated by {@code generate-pipe-template.js}.
     */
    private enum Dir {
        N, S, E, W, U, D
    }

    /** All 64 state names (index 0 = "Single", index 1–63 = bitmask combos). */
    private static final String[] ALL_STATES = buildAllStateNames();

    /** Populated at asset load time: state name → resolved block-type asset key. */
    private Map<String, String> stateToBlockKey;

    // -------------------------------------------------------------------------

    private static String[] buildAllStateNames() {
        Dir[] dirs = Dir.values(); // N, S, E, W, U, D (ordinals 0–5)
        String[] states = new String[64];
        states[0] = "Single";
        for (int mask = 1; mask < 64; mask++) {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 6; i++) {
                if ((mask & (1 << i)) != 0) {
                    sb.append(dirs[i].name());
                }
            }
            states[mask] = sb.toString();
        }
        return states;
    }

    // -------------------------------------------------------------------------
    // ConnectedBlockRuleSet contract

    @Override
    public boolean onlyUpdateOnPlacement() {
        // Re-evaluate whenever any neighbour changes, not just on first placement.
        return false;
    }

    @Override
    public void updateCachedBlockTypes(BlockType baseBlockType,
            BlockTypeAssetMap<String, BlockType> assetMap) {
        Map<String, String> map = new HashMap<>(64);
        for (String state : ALL_STATES) {
            String key = baseBlockType.getBlockKeyForState(state);
            if (key != null) {
                map.put(state, key);
            } else {
                LOGGER.warning("[PipeRuleSet] updateCachedBlockTypes: no block key for state=\"" + state
                        + "\" on base block \"" + baseBlockType.getId() + "\"");
            }
        }
        this.stateToBlockKey = map;
        LOGGER.info("[PipeRuleSet] updateCachedBlockTypes: resolved " + map.size()
                + "/64 states for base block \"" + baseBlockType.getId() + "\"");
    }

    @Override
    public Optional<ConnectedBlocksUtil.ConnectedBlockResult> getConnectedBlockType(
            World world, Vector3ic coordinate, BlockType currentBlockType,
            int rotation, Vector3ic placementNormal, boolean isPlacement) {

        if (stateToBlockKey == null) {
            LOGGER.warning("[PipeRuleSet] stateToBlockKey is null — updateCachedBlockTypes was never called for "
                    + (currentBlockType != null ? currentBlockType.getId() : "null"));
            return Optional.empty();
        }

        GridLookup selfLookup = GridLookup.resolve(world.getChunkStore(), coordinate);
        if (selfLookup == null) {
            LOGGER.warning("[PipeRuleSet] GridLookup.resolve returned null at " + coordinate);
            return Optional.empty();
        }

        GridComponent self = selfLookup.component();
        if (self.getGridType() == null) {
            LOGGER.warning("[PipeRuleSet] self GridComponent has null GridType at " + coordinate);
            return Optional.empty();
        }

        Set<Dir> active = EnumSet.noneOf(Dir.class);

        for (FacePlane face : self.getFaces()) {
            if (face.getMode() == FaceMode.CLOSED) {
                continue;
            }

            // Rotate the face normal from local/JSON space to world space.
            BlockFace worldNormal = GridFaceUtil.rotateBlockFace(face.getNormal(), selfLookup.rotation());
            Dir dir = normalToDir(worldNormal);
            if (dir == null) {
                continue;
            }

            // World position of the cell this face touches (filler offset also rotated).
            Vector3i worldFacePos = GridFaceUtil.rotateFacePosition(face.getPosition(), selfLookup.rotation());
            Vector3i adjacentPos = GridFaceUtil.addOffset(
                    GridFaceUtil.addOffset(selfLookup.originPos(), worldFacePos),
                    worldNormal);

            GridLookup neighborLookup = GridLookup.resolve(world.getChunkStore(), adjacentPos);
            if (neighborLookup == null) {
                continue;
            }

            GridComponent neighbor = neighborLookup.component();
            if (neighbor.getGridType() == null) {
                continue;
            }
            if (!neighbor.getGridType().id().equals(self.getGridType().id())) {
                continue;
            }

            // The neighbour must expose a compatible face pointing back at us.
            FacePlane neighborFace = GridFaceUtil.findMatchingFace(
                    neighbor, neighborLookup.originPos(),
                    neighborLookup.rotation(),
                    GridFaceUtil.opposite(worldNormal), adjacentPos);
            if (neighborFace == null) {
                continue;
            }
            if (neighborFace.getMode() == FaceMode.CLOSED) {
                continue;
            }
            if (!GridFaceUtil.areLinkable(face.getMode(), neighborFace.getMode())) {
                continue;
            }

            active.add(dir);
        }

        String stateName = active.isEmpty() ? "Single" : buildStateName(active);
        String blockKey = stateToBlockKey.get(stateName);
        if (blockKey == null) {
            LOGGER.warning("[PipeRuleSet] no blockKey for state=\"" + stateName + "\" at " + coordinate
                    + " — state missing from Pipe.json State.Definitions?");
            return Optional.empty();
        }
        return Optional.of(new ConnectedBlocksUtil.ConnectedBlockResult(blockKey, rotation));
    }

    // -------------------------------------------------------------------------
    // Helpers

    private static String buildStateName(Set<Dir> active) {
        // EnumSet iterates in enum-declaration order: N, S, E, W, U, D.
        StringBuilder sb = new StringBuilder();
        for (Dir d : active) {
            sb.append(d.name());
        }
        return sb.toString();
    }

    @Nullable
    private static Dir normalToDir(BlockFace face) {
        return switch (face) {
            case North -> Dir.N;
            case South -> Dir.S;
            case East -> Dir.E;
            case West -> Dir.W;
            case Up -> Dir.U;
            case Down -> Dir.D;
            default -> null;
        };
    }
}
