package dev.drav.glyphworks.transfer.state;

import java.util.EnumSet;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.hypixel.hytale.math.vector.Vector3i;
import com.hypixel.hytale.protocol.BlockFace;
import com.hypixel.hytale.server.core.universe.world.World;
import com.hypixel.hytale.server.core.universe.world.storage.ChunkStore;

import dev.drav.glyphworks.grid.component.FaceMode;
import dev.drav.glyphworks.grid.component.FacePlane;
import dev.drav.glyphworks.grid.component.GridComponent;
import dev.drav.glyphworks.grid.lookup.GridLookup;

/**
 * Computes the visual state name for a pipe block based on which faces are
 * linked.
 *
 * <p>
 * Grid {@link FacePlane} normals are already stored in world-space, so no
 * rotation
 * transform is needed. A face is considered active when the block at the
 * adjacent cell
 * resolves (via filler if needed) to a position in
 * {@link GridComponent#getNeighbors()}.
 *
 * <p>
 * Labels are always emitted in N→S→E→W→U→D order to match the state names
 * generated by {@code generate-pipe-template.js}.
 *
 * @deprecated Will be replaced by a more flexible grid state system.
 */
@Deprecated
public final class PipeStateComputer {

    /**
     * Canonical direction order matching generate-pipe-template.js DIRECTIONS
     * array.
     */
    private enum Dir {
        N, S, E, W, U, D
    }

    private PipeStateComputer() {
    }

    @Deprecated
    @Nonnull
    public static String compute(
            @Nonnull GridComponent pipe,
            @Nonnull Vector3i pos,
            @Nonnull World world) {
        ChunkStore chunkStore = world.getChunkStore();
        Set<Dir> active = EnumSet.noneOf(Dir.class);

        for (FacePlane face : pipe.getFaces()) {
            if (face.getMode() == FaceMode.CLOSED)
                continue;

            Dir dir = normalToDir(face.getNormal());
            if (dir == null)
                continue;

            // World cell adjacent to this face: origin + facePosition + faceNormal.
            // For a 1×1 block facePosition is (0,0,0); for a multi-block it offsets first.
            Vector3i candidatePos = addOffset(addOffset(pos, face.getPosition()), face.getNormal());

            // Resolve filler cells → origin, then check if that origin is a linked
            // neighbor.
            GridLookup neighborLookup = GridLookup.resolve(chunkStore, candidatePos);
            if (neighborLookup == null)
                continue;

            if (pipe.getNeighbors().contains(neighborLookup.originPos())) {
                active.add(dir);
            }
        }

        if (active.isEmpty())
            return "Single";

        // EnumSet iterates in declaration order (N, S, E, W, U, D) — matches
        // shapeNameFor.
        StringBuilder sb = new StringBuilder();
        for (Dir d : active)
            sb.append(d.name());
        return sb.toString();
    }

    @Nullable
    private static Dir normalToDir(BlockFace face) {
        return switch (face) {
            case North -> Dir.N;
            case South -> Dir.S;
            case East -> Dir.E;
            case West -> Dir.W;
            case Up -> Dir.U;
            case Down -> Dir.D;
            default -> null;
        };
    }

    private static Vector3i addOffset(Vector3i pos, BlockFace face) {
        return switch (face) {
            case North -> new Vector3i(pos.x, pos.y, pos.z - 1);
            case South -> new Vector3i(pos.x, pos.y, pos.z + 1);
            case East -> new Vector3i(pos.x + 1, pos.y, pos.z);
            case West -> new Vector3i(pos.x - 1, pos.y, pos.z);
            case Up -> new Vector3i(pos.x, pos.y + 1, pos.z);
            case Down -> new Vector3i(pos.x, pos.y - 1, pos.z);
            default -> pos;
        };
    }

    private static Vector3i addOffset(Vector3i pos, Vector3i offset) {
        return new Vector3i(pos.x + offset.x, pos.y + offset.y, pos.z + offset.z);
    }
}
