package dev.drav.glyphworks.transfer.state;

import java.util.EnumSet;
import java.util.Set;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import com.hypixel.hytale.math.vector.Vector3i;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.Rotation;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.RotationTuple;
import com.hypixel.hytale.server.core.universe.world.World;

import dev.drav.glyphworks.transfer.component.FaceMode;
import dev.drav.glyphworks.transfer.component.FacePlane;
import dev.drav.glyphworks.transfer.component.TransferComponent;

/**
 * Computes the visual state name for a pipe block based on which faces are linked.
 *
 * <p>Face relMin/relMax are stored in north-facing (authored) coordinates.
 * The block's placed yaw is applied when computing the world direction of each face,
 * so the state label (N/S/E/W/U/D) always reflects the actual world axis.
 *
 * <p>Labels are always emitted in N→S→E→W→U→D order to match the state names
 * generated by {@code generate-pipe-template.js}.
 */
public final class PipeStateComputer {

    /** Canonical direction order matching generate-pipe-template.js DIRECTIONS array. */
    private enum Dir { N, S, E, W, U, D }

    private PipeStateComputer() {}

    @Nonnull
    public static String compute(
            @Nonnull TransferComponent pipe,
            @Nonnull Vector3i pos,
            @Nonnull World world) {
        RotationTuple rotation = pipe.getRotation();
        Set<Dir> active = EnumSet.noneOf(Dir.class);

        for (FacePlane face : pipe.getFaces()) {
            if (face.getMode() == FaceMode.CLOSED) continue;
            if (face.getNeighborNodeId() == null) continue;

            Dir dir = worldDir(face.getRelMin(), face.getRelMax(), rotation);
            if (dir != null) active.add(dir);
        }

        if (active.isEmpty()) return "Single";

        // EnumSet iterates in declaration order (N, S, E, W, U, D) — matches shapeNameFor
        StringBuilder sb = new StringBuilder();
        for (Dir d : active) sb.append(d.name());
        return sb.toString();
    }

    @Nullable
    private static Dir worldDir(Vector3i relMin, Vector3i relMax, RotationTuple rotation) {
        Vector3i ra = rotatePitch(relMin, rotation.pitch());
        ra = rotateYaw(ra, rotation.yaw());
        ra = rotateRoll(ra, rotation.roll());
        Vector3i rb = rotatePitch(relMax, rotation.pitch());
        rb = rotateYaw(rb, rotation.yaw());
        rb = rotateRoll(rb, rotation.roll());
        int minX = Math.min(ra.x, rb.x), maxX = Math.max(ra.x, rb.x);
        int minY = Math.min(ra.y, rb.y), maxY = Math.max(ra.y, rb.y);
        int minZ = Math.min(ra.z, rb.z), maxZ = Math.max(ra.z, rb.z);

        if (minX == maxX) return minX == 1 ? Dir.E : Dir.W;
        if (minY == maxY) return minY == 1 ? Dir.U : Dir.D;
        if (minZ == maxZ) return minZ == 1 ? Dir.N : Dir.S;
        return null;
    }

    private static Vector3i rotateYaw(Vector3i v, Rotation yaw) {
        switch (yaw) {
            case Ninety:     return new Vector3i(v.z,     v.y, 1 - v.x);
            case OneEighty:  return new Vector3i(1 - v.x, v.y, 1 - v.z);
            case TwoSeventy: return new Vector3i(1 - v.z, v.y, v.x);
            default:         return new Vector3i(v.x,     v.y, v.z);
        }
    }

    private static Vector3i rotatePitch(Vector3i v, Rotation pitch) {
        switch (pitch) {
            case Ninety:     return new Vector3i(v.x, 1 - v.z, v.y);
            case OneEighty:  return new Vector3i(v.x, 1 - v.y, 1 - v.z);
            case TwoSeventy: return new Vector3i(v.x, v.z, 1 - v.y);
            default:         return new Vector3i(v.x, v.y, v.z);
        }
    }

    private static Vector3i rotateRoll(Vector3i v, Rotation roll) {
        switch (roll) {
            case Ninety:     return new Vector3i(1 - v.y, v.x, v.z);
            case OneEighty:  return new Vector3i(1 - v.x, 1 - v.y, v.z);
            case TwoSeventy: return new Vector3i(v.y, 1 - v.x, v.z);
            default:         return new Vector3i(v.x, v.y, v.z);
        }
    }
}
